FROM php:8.2-apache

# Instala extensiones necesarias de PHP para PostgreSQL
RUN apt-get update && apt-get install -y libpq-dev \
    && docker-php-ext-install pdo_pgsql pgsql
    
# Copia el código fuente al contenedor
COPY . /frontend

# Habilita mod_rewrite para URLs amigables
RUN a2enmod rewrite

# Asignar permisos adecuados y permitir acceso
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

EXPOSE 80